# Generated by Django 2.2.4 on 2020-03-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datesmod',
            old_name='todate',
            new_name='becausedate',
        ),
    ]
