# Generated by Django 2.2.7 on 2020-03-05 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLogDeliveryMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_ref_number', models.CharField(max_length=50)),
                ('type_of_biomass', models.CharField(max_length=50)),
                ('description_moisture_content', models.CharField(max_length=50)),
                ('source_supplier', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('BSL_Number', models.IntegerField()),
                ('delivery_note_number', models.IntegerField()),
                ('delivery_date', models.DateTimeField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_day', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
