# Generated by Django 2.2.4 on 2021-01-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fueldelivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellogdeliverymod',
            name='BSL_Number',
            field=models.IntegerField(blank=True, choices=[(None, ''), (123456, '123456'), (245456, '245456'), (666668, '666668'), (787878, '787878'), (9999887, '9999887')], null=True),
        ),
    ]
