from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(FuelLogSystemOneMod)
admin.site.register(monthlyMeterSystemOneMod)
admin.site.register(FuelLogSystemTwoMod)
admin.site.register(monthlyMeterSystemTwoMod)
admin.site.register(FuelLogSystemThreeMod)
admin.site.register(monthlyMeterSystemThreeMod)
admin.site.register(FuelLogSystemFourMod)
admin.site.register(monthlyMeterSystemFourMod)
admin.site.register(FuelLogSystemFiveMod)
admin.site.register(monthlyMeterSystemFiveMod)
admin.site.register(FuelLogSystemSixMod)
admin.site.register(monthlyMeterSystemSixMod)
admin.site.register(FuelLogSystemSevenMod)
admin.site.register(monthlyMeterSystemSevenMod)
admin.site.register(FuelLogSystemEightMod)
admin.site.register(monthlyMeterSystemEightMod)
admin.site.register(FuelLogSystemNineMod)
admin.site.register(monthlyMeterSystemNineMod)
admin.site.register(FuelLogSystemTenMod)
admin.site.register(monthlyMeterSystemTenMod)
