# Generated by Django 2.2.7 on 2020-03-05 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyMeterSystemOneMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(default='6000100118', max_length=50)),
                ('serial_number', models.CharField(default='80003356', max_length=50)),
                ('current_meter_reading', models.IntegerField(default=0)),
                ('previous_meter_reading', models.IntegerField(default=0)),
                ('difference', models.IntegerField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelLogSystemOneMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buckets_added', models.DecimalField(decimal_places=1, max_digits=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
