# Generated by Django 2.2.7 on 2020-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_fuellogsystemonemod_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellogsystemeightmod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemfivemod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemfourmod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemninemod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemsevenmod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemsixmod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemtenmod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemthreemod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fuellogsystemtwomod',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
