# Generated by Django 2.2.7 on 2020-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20200326_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellogsystemonemod',
            name='test',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=50),
            preserve_default=False,
        ),
    ]
