# Generated by Django 2.2.7 on 2020-04-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_fuellogsystemonemod_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuellogsystemonemod',
            name='test',
        ),
    ]
