# Generated by Django 2.2.7 on 2020-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_remove_fuellogsystemonemod_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellogsystemonemod',
            name='product',
            field=models.CharField(default='stuff', max_length=255),
            preserve_default=False,
        ),
    ]
