# Generated by Django 2.2.7 on 2020-04-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_fuellogsystemonemod_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuellogsystemonemod',
            name='product',
        ),
    ]
