# Generated by Django 2.2.7 on 2020-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_remove_fuellogsystemonemod_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellogsystemonemod',
            name='product',
            field=models.CharField(choices=[(1, 'BiomassOtherStuff'), (2, 'BiomassStuff')], default='BiomassStuff', max_length=255),
            preserve_default=False,
        ),
    ]
