# Generated by Django 2.2.7 on 2020-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_fuellogsystemonemod_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellogsystemonemod',
            name='product',
            field=models.IntegerField(choices=[(1, 'BiomassOtherStuff'), (2, 'BiomassStuff')], default=0),
        ),
    ]
