# Generated by Django 2.2.7 on 2020-04-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_auto_20200403_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellogsystemonemod',
            name='buckets_added',
            field=models.FloatField(),
        ),
    ]
