# Generated by Django 2.2.7 on 2020-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmod',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
