# Generated by Django 2.2.7 on 2020-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200403_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmod',
            name='stock',
            field=models.FloatField(),
        ),
    ]
